### ISSUE TITLE
Making API more idiomatic

### ISSUE THREAD

**Issue by maartenvanvliet** [allenan/magic-admin-elixir#1]
Hey, love your library and gonna use it in the coming time. 

I was wondering if you'd be open to making the api more idiomatic in Elixir. Mostly adding a `Token.validate` function so it returns an ok/error tuple, instead of the raising function?

I'll file a PR if you're okay with this.

**Comment by allenan** [comment]
hi @maartenvanvliet certainly open to a PR for this 🙏

**Comment by allenan** [comment]
went ahead and fixed in #3. thanks for the good suggestion @maartenvanvliet
